"""Weekly growth digest generator|||주간 성장 다이제스트 생성기."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from vxis.growth.changelog import ChangeLog
from vxis.growth.config import load_bootstrap_config

DIGESTS_DIR = Path("docs/growth-digests")


def generate_weekly_digest() -> Path:
    """Generate markdown digest for the past week|||지난 주 마크다운 다이제스트."""
    log = ChangeLog()
    summary = log.summary(days=7)

    now = datetime.now(timezone.utc)
    filename = f"{now.strftime('%Y-%m-%d')}.md"
    DIGESTS_DIR.mkdir(parents=True, exist_ok=True)
    out_path = DIGESTS_DIR / filename

    config = load_bootstrap_config()
    dry_run = bool(config["apply"]["dry_run"])

    lines: list[str] = [
        f"# VXIS Growth Weekly Digest — {now.strftime('%Y-%m-%d')}",
        "",
        "## Summary",
        f"- Total events: {summary['total_events']}",
        f"- Window: since {summary['since']}",
        "",
        "## Events by Type",
    ]
    for event_type, count in summary["by_type"].items():
        lines.append(f"- {event_type}: {count}")

    lines.extend(
        [
            "",
            "## Bootstrap Mode Status",
            f"- Dry-run: {'enabled' if dry_run else 'disabled'}",
            "",
            "_Generated by VXIS Growth Layer_",
        ]
    )

    out_path.write_text("\n".join(lines), encoding="utf-8")
    return out_path
