"""P6 Report — NCC Group style final report generation."""

from __future__ import annotations

from vxis.phases.base import DeadEndCriterion, PhaseGuide

PHASE_GUIDE = PhaseGuide(
    id="P6_report",
    name_en="Report Generation — NCC Group Style",
    name_ko="리포트 생성 — NCC Group 스타일",
    stage="report",
    parallel_group=8,
    depends_on=("P12_evolution", "P18_collective"),
    objective_en=(
        "Produce the final deliverable: a bilingual NCC Group style HTML "
        "report containing every finding, every chain, every alternative crown "
        "path, the 5-dimension VXIS score, the executive summary (LLM-generated), "
        "screenshots, MITRE ATT&CK mapping, CVSS scores, and remediation "
        "guidance. This is what the client reads. Runs AFTER learning phases "
        "so the report reflects the complete knowledge state."
    ),
    objective_ko=(
        "최종 결과물 생성: 모든 finding, 모든 chain, 모든 대체 크라운 경로, "
        "5-dimension VXIS 점수, LLM 생성 executive summary, 스크린샷, "
        "MITRE ATT&CK 매핑, CVSS 점수, 복구 가이드를 포함한 bilingual "
        "NCC Group 스타일 HTML 리포트 작성. 고객이 읽는 문서. Learning "
        "phase 이후 실행되어 완전한 지식 상태를 반영."
    ),
    entry_conditions=(
        "P12_evolution complete (gap analysis done)",
        "P18_collective complete (KB persisted)",
        "At least 1 finding recorded OR clean scan confirmed",
    ),
    recommended_primitives=(
        "vxis_enrich_findings",         # Brain enriches each finding (WHAT/HOW/IMPACT/PoC)
        "vxis_ai_summary",              # Executive summary via LLM
        "vxis_render_report",           # Jinja2 NCC template
        "vxis_attach_screenshots",      # Phase 4 captures
        "vxis_attack_graph_svg",        # Chain visualization
        "vxis_cvss_compute",            # CVSS v3.1 scores
        "vxis_mitre_mapping",           # ATT&CK technique mapping
        "vxis_score_compute",           # 5-dimension VXIS score
    ),
    mandatory_primitives=(
        "vxis_enrich_findings",
        "vxis_render_report",
    ),
    dead_end_criteria=(
        DeadEndCriterion(
            id="all_findings_enriched",
            description_en="Every finding has WHAT/HOW/IMPACT/PoC/ATTACK PATH filled",
            description_ko="모든 finding이 WHAT/HOW/IMPACT/PoC/ATTACK PATH 완성",
            check=lambda ctx: all(
                "WHAT" in getattr(f, "description", "")
                and "HOW" in getattr(f, "description", "")
                for f in getattr(ctx, "findings", [])
            ),
        ),
        DeadEndCriterion(
            id="report_file_exists",
            description_en="HTML report file successfully written",
            description_ko="HTML 리포트 파일 성공적으로 저장됨",
            check=lambda ctx: bool(getattr(ctx, "report_path", "")),
        ),
        DeadEndCriterion(
            id="score_computed",
            description_en="5-dimension VXIS score calculated",
            description_ko="5-dimension VXIS 점수 계산됨",
            check=lambda ctx: getattr(ctx, "vxis_score", None) is not None,
        ),
    ),
    success_criteria=(
        "reports/<scan_id>.html exists",
        "Report contains bilingual content (English + Korean)",
        "Executive summary generated by LLM",
        "All findings enriched to NCC Group spec",
        "5-dimension score present",
    ),
    blocking_errors=(
        "template_render_failure",
        "enrichment_llm_unreachable",
        "report_write_permission_denied",
    ),
    strategic_advice_en=(
        "This is the client-facing artifact. Quality matters more than speed. "
        "Every finding MUST have WHAT/HOW/IMPACT/PoC/ATTACK PATH per CLAUDE.md "
        "rules. Remediation MUST have Immediate/Short-term/Long-term sections. "
        "All content bilingual (English|||Korean). client_name stays English-only. "
        "Enrichment runs BEFORE template render — Brain gets one shot per finding. "
        "Use Phase 4 screenshots for visual proof. Use Phase 8 chain graph for "
        "attack path diagrams. Include all alternative crown paths from P11 "
        "mutation — the client needs to fix the root cause, not just one entry."
    ),
    strategic_advice_ko=(
        "고객이 보는 산출물. 속도보다 품질이 중요. 모든 finding은 CLAUDE.md "
        "규칙에 따라 반드시 WHAT/HOW/IMPACT/PoC/ATTACK PATH를 포함해야 한다. "
        "Remediation은 반드시 Immediate/Short-term/Long-term 섹션을 포함. "
        "모든 내용 bilingual (영어|||한국어). client_name은 영어 고정. "
        "Enrichment는 template render 전에 실행 — finding별 Brain 호출 1회. "
        "Phase 4 스크린샷으로 시각적 증거 제공. Phase 8 chain graph로 공격 "
        "경로 다이어그램 생성. P11 mutation의 모든 대체 크라운 경로 포함 — "
        "고객은 1개 진입점이 아니라 근본 원인을 고쳐야 한다."
    ),
    crown_hint_en=(
        "Report quality is VXIS's professional signature. A single missing "
        "field in a finding breaks client trust. The crown jewel section must "
        "show: (1) primary attack path, (2) all alternative paths, (3) root "
        "cause analysis, (4) concrete remediation with code examples. "
        "This phase runs LAST (parallel_group=8) so the report reflects the "
        "complete learning from P12 Evolution + P18 Collective — nothing is "
        "left out of the final artifact."
    ),
    crown_hint_ko=(
        "리포트 품질은 VXIS의 전문성 서명이다. finding의 필드 하나만 비어도 "
        "고객 신뢰가 무너진다. 크라운 주얼 섹션은 반드시: (1) 주 공격 경로, "
        "(2) 모든 대체 경로, (3) 근본 원인 분석, (4) 코드 예시가 포함된 구체적 "
        "복구 방안. 이 Phase는 마지막에 실행(parallel_group=8)되므로 P12 "
        "Evolution + P18 Collective의 완전한 학습 결과를 반영 — 최종 산출물에 "
        "빠진 것이 없다."
    ),
    max_duration_minutes=20,
    next_phase_hint=(),  # 마지막 Phase
)
