from __future__ import annotations

from vxis.agent.block.classifier import BlockClassifier, BlockKind


def test_cloudflare_block_is_classified_without_executing_bypass() -> None:
    response = {
        "status_code": 403,
        "headers": {"server": "cloudflare", "cf-ray": "abc-SJC"},
        "text": "<title>Attention Required! | Cloudflare</title> Sorry, you have been blocked.",
    }

    signal = BlockClassifier().inspect(response)

    assert signal.kind == BlockKind.WAF_SIGNATURE
    assert signal.detector == "cloudflare"
    assert signal.confidence >= 0.9
    assert signal.suggested_strategy == "encoding-mutation"
    assert any("cf-ray" in item for item in signal.evidence)


def test_cloudflare_normal_200_is_not_treated_as_block() -> None:
    response = {
        "status_code": 200,
        "headers": {"server": "cloudflare", "cf-ray": "abc-SJC"},
        "text": "<html>normal proxied response</html>",
    }

    signal = BlockClassifier().inspect(response)

    assert signal.kind == BlockKind.NONE
    assert signal.blocked is False
    assert signal.suggested_strategy is None


def test_rate_limit_uses_current_response_and_recent_history() -> None:
    history = [
        {"status_code": 200, "headers": {}, "text": "ok"},
        {"status_code": 429, "headers": {}, "text": "Too many requests"},
    ]
    response = {
        "status_code": 429,
        "headers": {"Retry-After": "60", "X-RateLimit-Remaining": "0"},
        "text": "request limit exceeded",
    }

    signal = BlockClassifier().inspect(response, history)

    assert signal.kind == BlockKind.WAF_RATE
    assert signal.detector == "generic-rate-limit"
    assert signal.suggested_strategy == "timing-jitter"
    assert "recent history contains 2 HTTP 429 responses" in signal.evidence


def test_known_vendor_signatures_are_detected() -> None:
    classifier = BlockClassifier()

    akamai = classifier.inspect(
        {
            "status": 403,
            "headers": {"Server": "AkamaiGHost"},
            "body": "Access Denied Reference #18.abc",
        }
    )
    incapsula = classifier.inspect(
        {
            "status_code": 403,
            "headers": {"X-Iinfo": "abc", "Set-Cookie": "visid_incap=1"},
            "text": "Request unsuccessful. Incapsula incident ID: 123",
        }
    )
    aws = classifier.inspect(
        {
            "status_code": 403,
            "headers": {"x-amzn-waf-action": "BLOCK"},
            "text": "Generated by AWS WAF",
        }
    )

    assert akamai.kind == BlockKind.WAF_SIGNATURE
    assert akamai.detector == "akamai"
    assert incapsula.kind == BlockKind.WAF_SIGNATURE
    assert incapsula.detector == "incapsula"
    assert aws.kind == BlockKind.WAF_SIGNATURE
    assert aws.detector == "aws-waf"


def test_explicit_honeypot_marker_wins_over_generic_status() -> None:
    signal = BlockClassifier().inspect(
        {
            "status_code": 403,
            "headers": {"X-Honeypot": "true"},
            "text": "forbidden honeypot trap endpoint",
        }
    )

    assert signal.kind == BlockKind.HONEYPOT
    assert signal.detector == "explicit-honeypot-marker"
    assert signal.suggested_strategy == "abandon-surface"
